project:
  type: website
  output-dir: docs

website:
  title: "TheoRegio"
  navbar:
    left:
      - href: index.qmd
        text: "Index"
      - href: geom_doc.qmd
        text: "Geométries" 
      - href: autocor.qmd
        text: "Autocorrélation (cours)"    
      - href: autocor_exo.qmd
        text: "Autocorrélation (exo)"  
      - href: classifregio.qmd
        text: "Classif./Regio. (cours)"  
      - href: classifregio_exo.qmd
        text: "Classif./Regio. (exo)"
    right: 
      - icon: github # add icons as navbar buttons
        href: https://github.com/worldregio/theoregio
        target: _blank
  page-footer:
    background: dark
    left: Copyright 2024, Claude Grasland
format:
  html:
    theme: 
      light: minty    
      dark: solar
    css: styles.css
    toc: true


